
services:
- type: web
name: playgallaryultimate
ENV: PYTHON
build: command
start: command
plan: free
branch: main
buildCommand: pip install -r requirement.txt
startCommand:          python app.py

autoDeploy: true
